(ns koraujkor.data
    (:require [reagent.core :as reagent]
              [datascript.core :as d]
              [posh.core :as p]))

(def jegyzékek-száma-keletkezési-hely-szerint
    [{
        :name "Ausztria"
        :data [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0 3 1 0 0 1 0 0 5 0 0 1 2 1 1 0 20 0 0 2 4 1 1 3 2 3 2 1 0 3 0 8 0 0 1 3 1 2 0 1 2 4 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 2 1 0 0 0 2 2 0 0 0 0 0 0 2 0 0 0 1 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
    }, {
        :name "Magyarország"
        :data [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 2 0 1 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 3 0 1 0 0 0 0 1 1 0 0 0 1 1 0 2 1 1 2 0 2 1 3 0 0 1 2 1 2 1 3 1 2 5 4 0 5 1 2 4 0 1 0 2 5 5 1 4 5 7 3 5 4 3 5 1 10 3 9 4 1 2 1 5 5 3 2 1 3 2 1 2 1 5 1 2 2 2 3 7 1 0 4 2 1 4 1 3 0 1 0 0 2 2 1 1 3 1 4 1 1 0 2 4 3 3 2 0 2 3 6 2 1 1 5 6 3 8 3 7 2 1 2 4 9 5 23 5 3 2 1 2 5 5 3 2 3 5 2 4 1 1 3 17 6 15 1 0 2 4 0 0 0 0]
    }, {
        :name "Románia"
        :data [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 1 2 1 1 1 0 1 2 3 2 3 1 2 0 2 0 0 0 4 0 0 2 2 0 0 0 2 1 0 3 2 0 1 1 1 0 2 2 0 0 1 0 2 3 4 1 1 3 3 1 1 1 4 6 2 6 2 1 3 1 1 0 0 1 6 8 1 3 9 2 4 7 4 3 2 4 3 3 2 1 14 3 2 3 1 7 3 4 3 2 3 7 5 3 6 6 3 4 9 3 2 7 2 6 1 1 7 7 7 2 3 2 2 13 3 2 7 7 7 4 4 6 7 4 2 4 1 5 5 3 0 2 5 0 5 3 0 6 3 6 2 2 3 1 3 5 0 6 4 0 6 1 3 5 3 8 2 3 9 2 5 4 0 2 5 6 1 10 3 0 0 0 0]
    }, {
        :name "Szlovákia"
        :data [2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 1 0 1 0 0 1 2 0 1 0 3 1 0 1 2 1 0 1 1 1 1 2 0 2 3 1 1 1 1 2 1 2 1 4 1 2 1 1 4 3 0 5 6 0 8 3 3 2 3 1 3 3 2 2 6 1 2 10 5 3 8 3 4 3 1 0 5 1 2 1 9 3 2 2 5 6 7 4 5 6 8 3 2 4 7 4 3 1 3 6 7 13 4 3 3 4 3 1 7 3 4 14 4 3 2 1 5 3 3 7 2 3 2 0 5 2 5 4 12 4 8 8 3 6 16 4 4 8 8 7 6 5 5 5 5 4 7 4 7 5 1 4 6 3 8 2 1 0 2 3 4 0 1 0 2 5 2 0 4 1 0 1 1 0 1 0 1 0 1 3 0 0 0 4 1 3 2 1 0 1 0 0 0 1 0 0 0 2 0 0 0 0 1 3 2 0 0 0 1]
    }])

(def psv0 [#_["Ország" ["Város" "Jegyzékek száma"]]
    ["Ausztria" ["Bécs" 8]
                ["Bécsújhely" 1]
                ["Borsmonostor" 1]
                ["Büdöskút" 1]
                ["Feketeváros" 1]
                ["Felsőlászló" 1]
                ["Fertőszéleskút" 1]
                ["Fraknó" 1]
                ["Graz" 2]
                ["Grossfeld" 1]
                ["Kabold" 2]
                ["Királyfalva" 1]
                ["Kisboldogasszony" 1]
                ["Kishöflány" 4]
                ["Kismarton" 5]
                ["Köpcsény" 1]
                ["Lajtapordány" 3]
                ["Lók" 1]
                ["Loretto" 1]
                ["Mannersdorff" 1]
                ["Marienburg" 1]
                ["Miklósfalva" 1]
                ["Missen" 1]
                ["Neithausen" 1]
                ["Németújvár" 11]
                ["Neustadt" 1]
                ["Nezsidér" 4]
                ["Northeim" 1]
                ["Nyulas" 1]
                ["Oroszvár" 2]
                ["Oszlop" 1]
                ["Pándorfalu" 1]
                ["Pordány" 1]
                ["Pottendorf" 3]
                ["Répcesarud" 1]
                ["Ruszt" 35]
                ["Somorja" 2]
                ["Sopronnyék" 2]
                ["Stolzenburg" 1]
                ["Szározvám" 2]
                ["Szentgyörgy" 1]
                ["Szentmargitbánya" 1]
                ["Tormafalu" 1]
                ["Védeny" 2]
                ["Völgyfalu" 1]
                ["Warmia" 1]
                ["Zundrava" 2]]
    ["Csehország" ["Prága" 1]]
    ["Hollandia" ["Amsterdam" 1]
                 ["Franeker" 4]
                 ["Utrecht" 1]]
    ["Horvátország" ["Csáktornya" 2]
                    ["Horvátkimle" 2]]
    ["Lengyelország" ["Boroszló" 3]]
    ["Magyarország" ["Abony" 1]
                    ["Alsónémedi" 2]
                    ["Altorja" 2]
                    ["Bag" 3]
                    ["Báji" 1]
                    ["Bercel" 1]
                    ["Berkesz" 1]
                    ["Bezenye" 1]
                    ["Bodok" 1]
                    ["Boldog" 2]
                    ["Buda" 16]
                    ["Buják" 4]
                    ["Csanak" 1]
                    ["Csongrád" 1]
                    ["Debrecen" 27]
                    ["Dömölk" 1]
                    ["Dunaharaszti" 1]
                    ["Dunakeszi" 1]
                    ["Ecseg" 6]
                    ["Ecser" 1]
                    ["Eger" 2]
                    ["Esztergom" 4]
                    ["Fegyvernek" 1]
                    ["Fertőszentmiklós" 1]
                    ["Galgamácsa" 2]
                    ["Gyöngyös" 3]
                    ["Győr" 2]
                    ["Harsány" 1]
                    ["Hatvan" 1]
                    ["Herencsény" 1]
                    ["Hévíz" 1]
                    ["Hódmezővásárhely" 1]
                    ["Hunfalva" 1]
                    ["Isaszeg" 1]
                    ["Jobbágyi" 6]
                    ["Kálló" 3]
                    ["Kecskemét" 1]
                    ["Kerepes" 1]
                    ["Keresd" 2]
                    ["Kóka" 6]
                    ["Korlát" 1]
                    ["Kosd" 1]
                    ["Körmend" 1]
                    ["Kőszeg" 27]
                    ["Lébény" 1]
                    ["Lőrinc" 1]
                    ["Mácsa" 1]
                    ["Magyarnádor" 2]
                    ["Magyaróvár" 1]
                    ["Mezőkövesd" 1]
                    ["Mosonmagyaróvár" 1]
                    ["Mosonszolnok" 1]
                    ["Nagyajta" 1]
                    ["Nagybresztovány" 1]
                    ["Nagykanizsa" 1]
                    ["Nagykáta" 2]
                    ["Nagykőrös" 1]
                    ["Nagylödő" 1]
                    ["Nézsa" 1]
                    ["Nógrád" 2]
                    ["Nógrádverőce" 1]
                    ["Noszlop" 1]
                    ["Nőtincs" 2]
                    ["Páli" 1]
                    ["Palotás" 2]
                    ["Pannonhalma" 3]
                    ["Pécel" 3]
                    ["Pécs" 2]
                    ["Pest" 5]
                    ["Rád" 1]
                    ["Regéc" 1]
                    ["Rékas" 1]
                    ["Romhány" 4]
                    ["Sári" 1]
                    ["Sárospatak" 21]
                    ["Sárvár" 2]
                    ["Sátoraljaújhely" 1]
                    ["Somogyvár" 1]
                    ["Sopron" 147]
                    ["Sűly" 1]
                    ["Sümeg" 3]
                    ["Szalánc" 1]
                    ["Szatmár" 6]
                    ["Szecső" 3]
                    ["Szente" 1]
                    ["Szentlászló" 2]
                    ["Szentlőrinckáta" 2]
                    ["Szentmártonkáta" 1]
                    ["Szentmihály" 1]
                    ["Sziget" 2]
                    ["Szőlős" 2]
                    ["Tápióbicske" 1]
                    ["Tápiószele" 1]
                    ["Tarcal" 1]
                    ["Tereske" 2]
                    ["Tiszafüred" 1]
                    ["Tiszaladány" 2]
                    ["Tóalmás" 5]
                    ["Tokaj" 1]
                    ["Tószeg" 2]
                    ["Tömörd" 1]
                    ["Turóc" 1]
                    ["Úri" 3]
                    ["Üllő" 2]
                    ["Vác" 3]
                    ["Vácszentlászló" 2]
                    ["Veresegyháza" 3]
                    ["Verseg" 1]
                    ["Veszprém" 1]
                    ["Vis" 1]
                    ["Vizkelet" 1]
                    ["Vízvár" 1]
                    ["Zsámbok" 2]]
    ["Németország" ["Drezda" 2]
                   ["Heidelberg" 2]
                   ["Tübingen" 1]
                   ["Ulm" 4]
                   ["Wittenberg" 1]]
    ["Olaszország" ["Bologna" 1]
                   ["Padova" 6]]
    ["Románia" ["Balázsfalva" 1]
               ["Bátos" 1]
               ["Belec" 2]
               ["Beszterce" 93]
               ["Borberek" 1]
               ["Brassó" 34]
               ["Brulya" 2]
               ["Csépán" 1]
               ["Csíksomlyó" 2]
               ["Dál" 1]
               ["Ebesfalva" 1]
               ["Egerbegy" 1]
               ["Erdély" 4]
               ["Fenyőfalva" 2]
               ["Fogaras" 8]
               ["Gerdály" 1]
               ["Gernyeszeg" 17]
               ["Gyergyóalfalu" 4]
               ["Gyergyószárhegy" 1]
               ["Gyulafehérvár" 17]
               ["Holcmány" 1]
               ["Kaplony" 1]
               ["Károlyvár" 1]
               ["Kispéterfalva" 1]
               ["Kolozsvár" 53]
               ["Lesses" 1]
               ["Malomárka" 1]
               ["Márkusfalva" 1]
               ["Marosvásárhely" 12]
               ["Mártonhegy" 2]
               ["Mikháza" 1]
               ["Nagybánya" 12]
               ["Nagyenyed" 12]
               ["Nagyszeben" 128]
               ["Nagyvárad" 1]
               ["Prépostfalva" 2]
               ["Radnót" 4]
               ["Rozsonda" 2]
               ["Rüsz" 1]
               ["Sajószentivány" 1]
               ["Segesvár" 50]
               ["Szászsebes" 1]
               ["Szászszentgyörgy" 1]
               ["Szászújfalu" 1]
               ["Szászváros" 1]
               ["Szászzalatna" 1]
               ["Szeben" 6]
               ["Székelyudvarhely" 10]
               ["Szentágota" 1]
               ["Tarcsafalva" 1]
               ["Torda" 4]
               ["Tövis" 1]
               ["Ujfalu" 1]
               ["Vajdahunyad" 1]
               ["Váldhíd" 1]
               ["Várad" 2]
               ["Zabola" 2]
               ["Zilah" 1]]
    ["Svájc" ["Basel" 2]]
    ["Szlovákia" ["Barskapronca" 3]
                 ["Bártfa" 8]
                 ["Beckó" 1]
                 ["Besztercebánya" 104]
                 ["Biccse" 1]
                 ["Cseklész" 1]
                 ["Csetnek" 1]
                 ["Csiffár" 2]
                 ["Divény" 2]
                 ["Eperjes" 23]
                 ["Érsekújvár" 2]
                 ["Ezeke" 1]
                 ["Farkasfalva" 1]
                 ["Felsőiszkáz" 1]
                 ["Felvidék" 2]
                 ["Fülek" 1]
                 ["Galgóc" 1]
                 ["Garamkürtös" 3]
                 ["Garammindszent" 3]
                 ["Garamszentbenedek" 17]
                 ["Garamszentkereszt" 3]
                 ["Garamszőllős" 1]
                 ["Garany" 1]
                 ["Huszt" 1]
                 ["Illava" 2]
                 ["Ipolyság" 1]
                 ["Jánosgyarmat" 1]
                 ["Jászó" 1]
                 ["Karvaly" 4]
                 ["Kassa" 83]
                 ["Kasza" 1]
                 ["Késmárk" 5]
                 ["Kiskeresnye" 1]
                 ["Kistapolcsány" 1]
                 ["Kisszeben" 1]
                 ["Komárom" 3]
                 ["Körmöcbánya" 37]
                 ["Lelesz" 4]
                 ["Léva" 2]
                 ["Losonc" 1]
                 ["Lőcse" 66]
                 ["Makovicza" 1]
                 ["Mátranovák" 1]
                 ["Modor" 1]
                 ["Mogyorómál" 2]
                 ["Nagylócsa" 1]
                 ["Nagysáros" 3]
                 ["Nagyszombat" 20]
                 ["Nagytapolcsány" 1]
                 ["Nyitra" 4]
                 ["Nyitrazávod" 2]
                 ["Pozsony" 28]
                 ["Pozsonybeszterce" 1]
                 ["Sasvár" 3]
                 ["Savnik" 1]
                 ["Selmecbánya" 85]
                 ["Sokolnitz" 1]
                 ["Szakolca" 5]
                 ["Szedikert" 1]
                 ["Szelnice" 1]
                 ["Szepeshely" 2]
                 ["Szepesvár" 1]
                 ["Szklabinya" 1]
                 ["Temetvény" 1]
                 ["Trencsén" 4]
                 ["Vágsellye" 1]
                 ["Verebély" 2]
                 ["Zólyom" 4]
                 ["Zsarnóca" 1]
                 ["Zsolna" 2]]
    ["Törökország" ["Konstantinápoly" 1]
                   ["Rodostó" 1]]
    ["Ukrajna" ["Munkács" 1]
               ["Ungvár" 7]]
])

(def psv1 [#_["Ország" ["Város" "Jegyzékek száma"]]
    ["Szlovákia" ["Besztercebánya" 104]
                 ["Selmecbánya" 85]
                 ["Kassa" 83]
                 ["Lőcse" 66]
                 ["Körmöcbánya" 37]
                 ["Pozsony" 28]
                 ["Eperjes" 23]
                 ["Nagyszombat" 20]
                 ["Garamszentbenedek" 17]
                 ["Bártfa" 8]
                 ["Szakolca" 5]
                 ["Késmárk" 5]
                 ["Zólyom" 4]
                 ["Trencsén" 4]
                 ["Nyitra" 4]
                 ["Lelesz" 4]
                 ["Karvaly" 4]
                 ["Sasvár" 3]
                 ["Nagysáros" 3]
                 ["Komárom" 3]
                 ["Garamszentkereszt" 3]
                 ["Garammindszent" 3]
                 ["Garamkürtös" 3]
                 ["Barskapronca" 3]
                 ["Zsolna" 2]
                 ["Verebély" 2]
                 ["Szepeshely" 2]
                 ["Nyitrazávod" 2]
                 ["Mogyorómál" 2]
                 ["Léva" 2]
                 ["Illava" 2]
                 ["Felvidék" 2]
                 ["Érsekújvár" 2]
                 ["Divény" 2]
                 ["Csiffár" 2]
                 ["Zsarnóca" 1]
                 ["Vágsellye" 1]
                 ["Temetvény" 1]
                 ["Szklabinya" 1]
                 ["Szepesvár" 1]
                 ["Szelnice" 1]
                 ["Szedikert" 1]
                 ["Sokolnitz" 1]
                 ["Savnik" 1]
                 ["Pozsonybeszterce" 1]
                 ["Nagytapolcsány" 1]
                 ["Nagylócsa" 1]
                 ["Modor" 1]
                 ["Mátranovák" 1]
                 ["Makovicza" 1]
                 ["Losonc" 1]
                 ["Kisszeben" 1]
                 ["Kistapolcsány" 1]
                 ["Kiskeresnye" 1]
                 ["Kasza" 1]
                 ["Jászó" 1]
                 ["Jánosgyarmat" 1]
                 ["Ipolyság" 1]
                 ["Huszt" 1]
                 ["Garany" 1]
                 ["Garamszőllős" 1]
                 ["Galgóc" 1]
                 ["Fülek" 1]
                 ["Felsőiszkáz" 1]
                 ["Farkasfalva" 1]
                 ["Ezeke" 1]
                 ["Csetnek" 1]
                 ["Cseklész" 1]
                 ["Biccse" 1]
                 ["Beckó" 1]]
    ["Románia" ["Nagyszeben" 128]
               ["Beszterce" 93]
               ["Kolozsvár" 53]
               ["Segesvár" 50]
               ["Brassó" 34]
               ["Gyulafehérvár" 17]
               ["Gernyeszeg" 17]
               ["Nagyenyed" 12]
               ["Nagybánya" 12]
               ["Marosvásárhely" 12]
               ["Székelyudvarhely" 10]
               ["Fogaras" 8]
               ["Szeben" 6]
               ["Torda" 4]
               ["Radnót" 4]
               ["Gyergyóalfalu" 4]
               ["Erdély" 4]
               ["Zabola" 2]
               ["Várad" 2]
               ["Rozsonda" 2]
               ["Prépostfalva" 2]
               ["Mártonhegy" 2]
               ["Fenyőfalva" 2]
               ["Csíksomlyó" 2]
               ["Brulya" 2]
               ["Belec" 2]
               ["Zilah" 1]
               ["Váldhíd" 1]
               ["Vajdahunyad" 1]
               ["Ujfalu" 1]
               ["Tövis" 1]
               ["Tarcsafalva" 1]
               ["Szentágota" 1]
               ["Szászzalatna" 1]
               ["Szászváros" 1]
               ["Szászújfalu" 1]
               ["Szászszentgyörgy" 1]
               ["Szászsebes" 1]
               ["Sajószentivány" 1]
               ["Rüsz" 1]
               ["Nagyvárad" 1]
               ["Mikháza" 1]
               ["Márkusfalva" 1]
               ["Malomárka" 1]
               ["Lesses" 1]
               ["Kispéterfalva" 1]
               ["Károlyvár" 1]
               ["Kaplony" 1]
               ["Holcmány" 1]
               ["Gyergyószárhegy" 1]
               ["Gerdály" 1]
               ["Egerbegy" 1]
               ["Ebesfalva" 1]
               ["Dál" 1]
               ["Csépán" 1]
               ["Borberek" 1]
               ["Bátos" 1]
               ["Balázsfalva" 1]]
    ["Magyarország" ["Sopron" 147]
                    ["Kőszeg" 27]
                    ["Debrecen" 27]
                    ["Sárospatak" 21]
                    ["Buda" 16]
                    ["Szatmár" 6]
                    ["Kóka" 6]
                    ["Jobbágyi" 6]
                    ["Ecseg" 6]
                    ["Tóalmás" 5]
                    ["Pest" 5]
                    ["Romhány" 4]
                    ["Esztergom" 4]
                    ["Buják" 4]
                    ["Veresegyháza" 3]
                    ["Vác" 3]
                    ["Úri" 3]
                    ["Szecső" 3]
                    ["Sümeg" 3]
                    ["Pécel" 3]
                    ["Pannonhalma" 3]
                    ["Kálló" 3]
                    ["Gyöngyös" 3]
                    ["Bag" 3]
                    ["Zsámbok" 2]
                    ["Vácszentlászló" 2]
                    ["Üllő" 2]
                    ["Tószeg" 2]
                    ["Tiszaladány" 2]
                    ["Tereske" 2]
                    ["Szőlős" 2]
                    ["Sziget" 2]
                    ["Szentlőrinckáta" 2]
                    ["Szentlászló" 2]
                    ["Sárvár" 2]
                    ["Pécs" 2]
                    ["Palotás" 2]
                    ["Nőtincs" 2]
                    ["Nógrád" 2]
                    ["Nagykáta" 2]
                    ["Magyarnádor" 2]
                    ["Keresd" 2]
                    ["Győr" 2]
                    ["Galgamácsa" 2]
                    ["Eger" 2]
                    ["Boldog" 2]
                    ["Altorja" 2]
                    ["Alsónémedi" 2]
                    ["Vízvár" 1]
                    ["Vizkelet" 1]
                    ["Vis" 1]
                    ["Veszprém" 1]
                    ["Verseg" 1]
                    ["Turóc" 1]
                    ["Tömörd" 1]
                    ["Tokaj" 1]
                    ["Tiszafüred" 1]
                    ["Tarcal" 1]
                    ["Tápiószele" 1]
                    ["Tápióbicske" 1]
                    ["Szentmihály" 1]
                    ["Szentmártonkáta" 1]
                    ["Szente" 1]
                    ["Szalánc" 1]
                    ["Sűly" 1]
                    ["Somogyvár" 1]
                    ["Sátoraljaújhely" 1]
                    ["Sári" 1]
                    ["Rékas" 1]
                    ["Regéc" 1]
                    ["Rád" 1]
                    ["Páli" 1]
                    ["Noszlop" 1]
                    ["Nógrádverőce" 1]
                    ["Nézsa" 1]
                    ["Nagylödő" 1]
                    ["Nagykőrös" 1]
                    ["Nagykanizsa" 1]
                    ["Nagybresztovány" 1]
                    ["Nagyajta" 1]
                    ["Mosonszolnok" 1]
                    ["Mosonmagyaróvár" 1]
                    ["Mezőkövesd" 1]
                    ["Magyaróvár" 1]
                    ["Mácsa" 1]
                    ["Lőrinc" 1]
                    ["Lébény" 1]
                    ["Körmend" 1]
                    ["Kosd" 1]
                    ["Korlát" 1]
                    ["Kerepes" 1]
                    ["Kecskemét" 1]
                    ["Isaszeg" 1]
                    ["Hunfalva" 1]
                    ["Hódmezővásárhely" 1]
                    ["Hévíz" 1]
                    ["Herencsény" 1]
                    ["Hatvan" 1]
                    ["Harsány" 1]
                    ["Fertőszentmiklós" 1]
                    ["Fegyvernek" 1]
                    ["Ecser" 1]
                    ["Dunakeszi" 1]
                    ["Dunaharaszti" 1]
                    ["Dömölk" 1]
                    ["Csongrád" 1]
                    ["Csanak" 1]
                    ["Bodok" 1]
                    ["Bezenye" 1]
                    ["Berkesz" 1]
                    ["Bercel" 1]
                    ["Báji" 1]
                    ["Abony" 1]]
    ["Ausztria" ["Ruszt" 35]
                ["Németújvár" 11]
                ["Bécs" 8]
                ["Kismarton" 5]
                ["Nezsidér" 4]
                ["Kishöflány" 4]
                ["Pottendorf" 3]
                ["Lajtapordány" 3]
                ["Zundrava" 2]
                ["Védeny" 2]
                ["Szározvám" 2]
                ["Sopronnyék" 2]
                ["Somorja" 2]
                ["Oroszvár" 2]
                ["Kabold" 2]
                ["Graz" 2]
                ["Warmia" 1]
                ["Völgyfalu" 1]
                ["Tormafalu" 1]
                ["Szentmargitbánya" 1]
                ["Szentgyörgy" 1]
                ["Stolzenburg" 1]
                ["Répcesarud" 1]
                ["Pordány" 1]
                ["Pándorfalu" 1]
                ["Oszlop" 1]
                ["Nyulas" 1]
                ["Northeim" 1]
                ["Neustadt" 1]
                ["Neithausen" 1]
                ["Missen" 1]
                ["Miklósfalva" 1]
                ["Marienburg" 1]
                ["Mannersdorff" 1]
                ["Loretto" 1]
                ["Lók" 1]
                ["Köpcsény" 1]
                ["Kisboldogasszony" 1]
                ["Királyfalva" 1]
                ["Grossfeld" 1]
                ["Fraknó" 1]
                ["Fertőszéleskút" 1]
                ["Felsőlászló" 1]
                ["Feketeváros" 1]
                ["Büdöskút" 1]
                ["Borsmonostor" 1]
                ["Bécsújhely" 1]]
    ["Németország" ["Ulm" 4]
                   ["Heidelberg" 2]
                   ["Drezda" 2]
                   ["Wittenberg" 1]
                   ["Tübingen" 1]]
    ["Ukrajna" ["Ungvár" 7]
               ["Munkács" 1]]
    ["Olaszország" ["Padova" 6]
                   ["Bologna" 1]]
    ["Hollandia" ["Franeker" 4]
                 ["Utrecht" 1]
                 ["Amsterdam" 1]]
    ["Horvátország" ["Horvátkimle" 2]
                    ["Csáktornya" 2]]
    ["Lengyelország" ["Boroszló" 3]]
    ["Svájc" ["Basel" 2]]
    ["Törökország" ["Rodostó" 1]
                   ["Konstantinápoly" 1]]
    ["Csehország" ["Prága" 1]]
])

(def psv2 [#_["Ország" ["Város" "Jegyzékek száma"]]
    ["Szlovákia" ["Besztercebánya" 104]
                 ["Selmecbánya" 85]
                 ["Kassa" 83]
                 ["Lőcse" 66]
                 ["Körmöcbánya" 37]
                 ["Pozsony" 28]
                 ["Eperjes" 23]
                 ["Nagyszombat" 20]
                 ["Garamszentbenedek" 17]
                 ["Bártfa" 8]
                 ["Szakolca" 5]
                 ["Késmárk" 5]]
    ["Románia" ["Nagyszeben" 128]
               ["Beszterce" 93]
               ["Kolozsvár" 53]
               ["Segesvár" 50]
               ["Brassó" 34]
               ["Gyulafehérvár" 17]
               ["Gernyeszeg" 17]
               ["Nagyenyed" 12]
               ["Nagybánya" 12]
               ["Marosvásárhely" 12]
               ["Székelyudvarhely" 10]
               ["Fogaras" 8]
               ["Szeben" 6]]
    ["Magyarország" ["Sopron" 147]
                    ["Kőszeg" 27]
                    ["Debrecen" 27]
                    ["Sárospatak" 21]
                    ["Buda" 16]
                    ["Szatmár" 6]
                    ["Kóka" 6]
                    ["Jobbágyi" 6]
                    ["Ecseg" 6]
                    ["Tóalmás" 5]
                    ["Pest" 5]]
    ["Ausztria" ["Ruszt" 35]
                ["Németújvár" 11]
                ["Bécs" 8]
                ["Kismarton" 5]]
    ["Ukrajna" ["Ungvár" 7]]
    ["Olaszország" ["Padova" 6]]
])

(def psv3 [#_["Ország" ["Város" "Jegyzékek száma"]]
    ["Szlovákia" ["Besztercebánya" 104]
                 ["Selmecbánya" 85]
                 ["Kassa" 83]
                 ["Lőcse" 66]
                 ["Körmöcbánya" 37]
                 ["Pozsony" 28]
                 ["Eperjes" 23]
                 ["Nagyszombat" 20]
                 ["Garamszentbenedek" 17]
                 ["Bártfa" 8]
                 ["Szakolca" 5]
                 ["Késmárk" 5]
                 ["Zólyom" 4]
                 ["Trencsén" 4]
                 ["Nyitra" 4]
                 ["Lelesz" 4]
                 ["Karvaly" 4]
                 ["Sasvár" 3]
                 ["Nagysáros" 3]
                 ["Komárom" 3]
                 ["Garamszentkereszt" 3]
                 ["Garammindszent" 3]
                 ["Garamkürtös" 3]
                 ["Barskapronca" 3]]
    ["Románia" ["Nagyszeben" 128]
               ["Beszterce" 93]
               ["Kolozsvár" 53]
               ["Segesvár" 50]
               ["Brassó" 34]
               ["Gyulafehérvár" 17]
               ["Gernyeszeg" 17]
               ["Nagyenyed" 12]
               ["Nagybánya" 12]
               ["Marosvásárhely" 12]
               ["Székelyudvarhely" 10]
               ["Fogaras" 8]
               ["Szeben" 6]
               ["Torda" 4]
               ["Radnót" 4]
               ["Gyergyóalfalu" 4]
               ["Erdély" 4]]
    ["Magyarország" ["Sopron" 147]
                    ["Kőszeg" 27]
                    ["Debrecen" 27]
                    ["Sárospatak" 21]
                    ["Buda" 16]
                    ["Szatmár" 6]
                    ["Kóka" 6]
                    ["Jobbágyi" 6]
                    ["Ecseg" 6]
                    ["Tóalmás" 5]
                    ["Pest" 5]
                    ["Romhány" 4]
                    ["Esztergom" 4]
                    ["Buják" 4]
                    ["Veresegyháza" 3]
                    ["Vác" 3]
                    ["Úri" 3]
                    ["Szecső" 3]
                    ["Sümeg" 3]
                    ["Pécel" 3]
                    ["Pannonhalma" 3]
                    ["Kálló" 3]
                    ["Gyöngyös" 3]
                    ["Bag" 3]]
    ["Ausztria" ["Ruszt" 35]
                ["Németújvár" 11]
                ["Bécs" 8]
                ["Kismarton" 5]
                ["Nezsidér" 4]
                ["Kishöflány" 4]
                ["Pottendorf" 3]
                ["Lajtapordány" 3]]
    ["Ukrajna" ["Ungvár" 7]]
    ["Olaszország" ["Padova" 6]]
    ["Németország" ["Ulm" 4]]
    ["Hollandia" ["Franeker" 4]]
    ["Lengyelország" ["Boroszló" 3]]
])

(def psv4 [#_["Nagyobb földrajzi egység" ["Település" "Jegyzékek száma"]]
    ["Felföld" ["Besztercebánya" 104]
               ["Selmecbánya" 85]
               ["Kassa" 83]
               ["Lőcse" 66]
               ["Körmöcbánya" 37]
               ["Pozsony" 28]
               ["Eperjes" 23]
               ["Sárospatak" 21]
               ["Nagyszombat" 20]
               ["Garamszentbenedek" 17]
               ["Bártfa" 8]
               ["Ungvár" 7]
               ["Késmárk" 5]
               ["Szakolca" 5]
               ["Karvaly" 4]
               ["Lelesz" 4]
               ["Nyitra" 4]
               ["Trencsén" 4]
               ["Barskapronca" 3]
               ["Garamkürtös" 3]
               ["Garammindszent" 3]
               ["Garamszentkereszt" 3]
               ["Nagysáros" 3]
               ["Sasvár" 3]
               ["Zólyom" 3]
               ["Belec" 2]
               ["Csiffár" 2]
               ["Divény" 2]
               ["Érsekújvár" 2]
               ["Felvidék" 2]
               ["Illava" 2]
               ["Kisszeben" 2]
               ["Léva" 2]
               ["Mogyorómál" 2]
               ["Nyitrazávod" 2]
               ["Szepeshely" 2]
               ["Verebély" 2]
               ["Zsolna" 2]
               ["Báji" 1]
               ["Beckó" 1]
               ["Biccse" 1]
               ["Bodok" 1]
               ["Cseklész" 1]
               ["Csetnek" 1]
               ["Ezeke" 1]
               ["Farkasfalva" 1]
               ["Fülek" 1]
               ["Galgóc" 1]
               ["Garamszőllős" 1]
               ["Garany" 1]
               ["Gömör megye" 1]
               ["Hajnik" 1]
               ["Hunfalva" 1]
               ["Ipolyság" 1]
               ["Jánosgyarmat" 1]
               ["Jászó" 1]
               ["Karancs Beriny" 1]
               ["Kasza" 1]
               ["Kiskeresnye" 1]
               ["Kistapolcsány" 1]
               ["Korlát" 1]
               ["Losonc" 1]
               ["Makovicza" 1]
               ["Márkusfalva" 1]
               ["Missen" 1]
               ["Modor" 1]
               ["Munkács" 1]
               ["Nagybresztovány" 1]
               ["Nagylócsa" 1]
               ["Nagytapolcsány" 1]
               ["Pozsonybeszterce" 1]
               ["Regéc" 1]
               ["Sátoraljaújhely" 1]
               ["Savnik" 1]
               ["Stolzenburg" 1]
               ["Szalánc" 1]
               ["Szedikert" 1]
               ["Szelnice" 1]
               ["Szentmihály" 1]
               ["Szepesvár" 1]
               ["Szklabinya" 1]
               ["Temetvény" 1]
               ["Turóc" 1]
               ["Vágsellye" 1]
               ["Zólyom vármegye" 1]
               ["Zsarnóca" 1]]
    ["Erdély" ["Nagyszeben" 133]
              ["Beszterce" 93]
              ["Kolozsvár" 53]
              ["Segesvár" 50]
              ["Brassó" 34]
              ["Gernyeszeg" 19]
              ["Gyulafehérvár" 18]
              ["Marosvásárhely" 12]
              ["Nagyenyed" 12]
              ["Székelyudvarhely" 10]
              ["Fogaras" 8]
              ["Erdély" 4]
              ["Gyergyóalfalu" 4]
              ["Radnót" 4]
              ["Torda" 4]
              ["Keresd" 3]
              ["Altorja" 2]
              ["Brulya" 2]
              ["Csíksomlyó" 2]
              ["Fenyőfalva" 2]
              ["Mártonhegy" 2]
              ["Prépostfalva" 2]
              ["Rozsonda" 2]
              ["Szászváros" 2]
              ["Zabola" 2]
              ["Balázsfalva" 1]
              ["Bátos" 1]
              ["Borberek" 1]
              ["Borsmonostor" 1]
              ["Csépán" 1]
              ["Csíkszentmihály" 1]
              ["Dál" 1]
              ["Ebesfalva" 1]
              ["Egerbegy" 1]
              ["Gerdály" 1]
              ["Grossfeld" 1]
              ["Gyergyószárhegy" 1]
              ["Holcmány" 1]
              ["Homoródszentmárton v. Ürmös" 1]
              ["Huszt" 1]
              ["Keresztényfalva" 1]
              ["Kispéterfalva" 1]
              ["Lesses" 1]
              ["Malomárka" 1]
              ["Marienburg" 1]
              ["Mátranovák" 1]
              ["Mikháza" 1]
              ["Nagyajta" 1]
              ["Netus" 1]
              ["Rüsz" 1]
              ["Sajószentivány" 1]
              ["Szászsebes" 1]
              ["Szászszentgyörgy" 1]
              ["Szászújfalu" 1]
              ["Szászzalatna" 1]
              ["Szentágota" 1]
              ["Tarcsafalva" 1]
              ["Tövis" 1]
              ["Vajdahunyad" 1]
              ["Váldhíd" 1]]
    ["Nyugat Magyarország" ["Sopron" 147]
                           ["Ruszt" 35]
                           ["Kőszeg" 27]
                           ["Németújvár" 11]
                           ["Kismarton" 5]
                           ["Kishöflány" 4]
                           ["Nezsidér" 4]
                           ["Lajtapordány" 3]
                           ["Pottendorff" 3]
                           ["Kabold" 2]
                           ["Oroszvár" 2]
                           ["Somorja" 2]
                           ["Sopronnyék" 2]
                           ["Szározvám" 2]
                           ["Védeny" 2]
                           ["Zundrava" 2]
                           ["Büdöskút" 1]
                           ["Feketeváros" 1]
                           ["Felsőlászló" 1]
                           ["Fertőszéleskút" 1]
                           ["Fraknó" 1]
                           ["Hof am Leithagebirge" 1]
                           ["Királyfalva" 1]
                           ["Kisboldogasszony" 1]
                           ["Köpcsény" 1]
                           ["Lók" 1]
                           ["Loretto" 1]
                           ["Mannersdorff" 1]
                           ["Miklósfalva" 1]
                           ["Nyulas" 1]
                           ["Oszlop" 1]
                           ["Pándorfalu" 1]
                           ["Pordány" 1]
                           ["Répcesarud" 1]
                           ["Szentgyörgy" 1]
                           ["Szentmargitbánya" 1]
                           ["Tormafalu" 1]
                           ["Ujfalu" 1]
                           ["Völgyfalu" 1]]
    ["Alföld" ["Debrecen" 27]
              ["Ecseg" 6]
              ["Jobbágyi" 6]
              ["Kóka" 6]
              ["Pest" 5]
              ["Tóalmás" 5]
              ["Buják" 4]
              ["Romhány" 4]
              ["Bag" 3]
              ["Gyöngyös" 3]
              ["Kálló" 3]
              ["Pécel" 3]
              ["Szecső" 3]
              ["Úri" 3]
              ["Vác" 3]
              ["Veresegyháza" 3]
              ["Alsónémedi" 2]
              ["Boldog" 2]
              ["Eger" 2]
              ["Galgamácsa" 2]
              ["Magyarnádor" 2]
              ["Nagykáta" 2]
              ["Nógrád" 2]
              ["Nőtincs" 2]
              ["Palotás" 2]
              ["Szentlászló" 2]
              ["Szentlőrinckáta" 2]
              ["Sziget" 2]
              ["Szőlős" 2]
              ["Tereske" 2]
              ["Tiszaladány" 2]
              ["Tószeg" 2]
              ["Üllő" 2]
              ["Vácszentlászló" 2]
              ["Abony" 1]
              ["Bercel" 1]
              ["Berkesz" 1]
              ["Csongrád" 1]
              ["Dunaharaszti" 1]
              ["Dunakeszi" 1]
              ["Ecser" 1]
              ["Fegyvernek" 1]
              ["Harsány" 1]
              ["Hatvan" 1]
              ["Herencsény" 1]
              ["Hódmezővásárhely" 1]
              ["Isaszeg" 1]
              ["Kecskemét" 1]
              ["Kerepes" 1]
              ["Kosd" 1]
              ["Lőrinc" 1]
              ["Mácsa" 1]
              ["Mezőkövesd" 1]
              ["Nagykőrös" 1]
              ["Nézsa" 1]
              ["Nógrádverőce" 1]
              ["Rád" 1]
              ["Rékas" 1]
              ["Sári" 1]
              ["Sokolnitz" 1]
              ["Sűly" 1]
              ["Szente" 1]
              ["Szentmártonkáta" 1]
              ["Tápióbicske" 1]
              ["Tápiósüly" 1]
              ["Tápiószele" 1]
              ["Tarcal" 1]
              ["Tiszafüred" 1]
              ["Tokaj" 1]
              ["váci egyházmegye" 1]
              ["Verseg" 1]
              ["Vis" 1]]
    ["Dunántúl" ["Buda" 16]
                ["Esztergom" 4]
                ["Komárom" 3]
                ["Pannonhalma" 3]
                ["Sümeg" 3]
                ["Csáktornya" 2]
                ["Győr" 2]
                ["Horvátkimle" 2]
                ["Pécs" 2]
                ["Sárvár" 2]
                ["Zsámbok" 2]
                ["Bezenye" 1]
                ["Csanak" 1]
                ["Dömölk" 1]
                ["Felsőiszkáz" 1]
                ["Fertőszentmiklós" 1]
                ["Hévíz" 1]
                ["Komárom megye" 1]
                ["Körmend" 1]
                ["Lébény" 1]
                ["Magyaróvár" 1]
                ["Mosonmagyaróvár" 1]
                ["Mosonszolnok" 1]
                ["Nagykanizsa" 1]
                ["Nagylödő" 1]
                ["Noszlop" 1]
                ["Páli" 1]
                ["Somogyvár" 1]
                ["Tömörd" 1]
                ["Veszprém" 1]
                ["Vizkelet" 1]
                ["Vízvár" 1]]
    ["Partium" ["Nagybánya" 12]
               ["Szatmár" 6]
               ["Várad" 2]
               ["Kaplony" 1]
               ["Nagyvárad" 1]
               ["Zilah" 1]]
    ["Ausztria" ["Bécs" 8]
                ["Grác" 2]
                ["Bécsújhely" 1]]
    ["Németország" ["Ulm" 4]
                   ["Drezda" 2]
                   ["Heidelberg" 2]
                   ["Northeim" 1]
                   ["Tübingen" 1]
                   ["Wittenberg" 1]]
    ["Olaszország" ["Padova" 6]
                   ["Bologna" 1]]
    ["Hollandia" ["Franeker" 4]
                 ["Amsterdam" 1]
                 ["Utrecht" 1]]
    ["Lengyelország" ["Boroszló" 3]
                     ["Warmia" 1]]
    ["Svájc" ["Bázel" 2]]
    ["Törökország" ["Konstantinápoly" 1]
                   ["Rodostó" 1]]
    ["Csehország" ["Prága" 1]]
])

(defonce tulajdonosok-élete (reagent/atom
[
    ["Zay Ferenc"             true  1505 1570]
    ["Thurzó (II.) Szaniszló" true  1531 1586]
    ["Illésházy István"       true  1540 1609]
    ["Báthory András"         true  1566 1599]
    ["Forgách Ferenc"         true  1566 1615]
    ["Thurzó (V.) György"     true  1567 1616]
    ["Esterházy Miklós"       true  1582 1645]
    ["Rákóczi György, I."     true  1593 1648]
    ["Rákóczi Pál"            true  1596 1636]
    ["Batthyány I. Ádám"      true  1609 1659]
    ["Bethlen János"          true  1613 1678]
    ["Thököly Zsigmond"       true  1618 1678]
    ["Zrínyi Miklós"          true  1620 1664]
    ["Zrínyi Péter"           true  1621 1671]
    ["Rákóczi Zsigmond, IV."  true  1622 1652]
    ["Nádasdy Ferenc"         true  1625 1671]
    ["Batthyány I. Pál"       true  1629 1674]
    ["Apafi Mihály, I."       true  1629 1690]
    ["Batthyány II. Kristóf"  true  1632 1685]
    ["Teleki I. Mihály"       true  1634 1690]
    ["Csáky István"           true  1635 1699]
    ["Eszterházy Pál"         true  1635 1713]
    ["Bethlen Miklós"         true  1642 1716]
    ["Bethlen Elek"           true  1645 1696]
    ["Rákóczi Erzsébet"       false 1655 1707]
    ["Thököly Imre"           true  1657 1705]
    ["Batthyány II. Ádám"     true  1662 1703]
    ["Teleki János"           true  1663 1679]
    ["Apafi Mihály, II."      true  1676 1713]
    ["Rákóczi Ferenc, II."    true  1676 1735]
    ["Teleki Pál"             true  1677 1731]
    ["Bethlen Kata"           false 1700 1759]
]))

(defonce tempid (let [n (atom 0)] (fn [] (swap! n dec))))

(def schema {})

(def conn (d/create-conn schema))

(d/transact! conn (mapv (fn [[a b c d]] {:db/id (tempid) :pers/name a :pers/male b :pers/born c :pers/dead d}) @tulajdonosok-élete))

(p/posh! conn)
